{-

  Problem 2

  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
-}

main = print $ sumation


-- フィボナッチ数列を得る
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

--
sumation = sum [x | x <- takeWhile (< 4000000) fibs, mod x 2 == 0]

-- フィボナッチ数列の第n項を得る
fib :: Int -> Int
fib 0 = 1
fib 1 = 1
fib n = fib (n - 1) + fib (n - 2)
